# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Coppeno < Formula
  desc "coppeno"
  homepage "https://github.com/webcyou-org/coppeno"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/webcyou-org/coppeno/releases/download/v0.6.0/coppeno_darwin_x86_64.tar.gz"
      sha256 "dbb4d7d3edc49b4c2ebfa0fe4fac5af3347e1f9464746139a480ad8d7e47d049"

      def install
        bin.install "coppeno"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/webcyou-org/coppeno/releases/download/v0.6.0/coppeno_darwin_arm64.tar.gz"
      sha256 "5afada7a6a34f11f8095acaf254d6af1de1008cb12f4f779ce239895bf1cdc20"

      def install
        bin.install "coppeno"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/webcyou-org/coppeno/releases/download/v0.6.0/coppeno_linux_x86_64.tar.gz"
      sha256 "93321508acd25b3b0092813dba558b8b95dfe6e6f60df07ef3e560fbb79d4bad"

      def install
        bin.install "coppeno"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/webcyou-org/coppeno/releases/download/v0.6.0/coppeno_linux_arm64.tar.gz"
      sha256 "89e4d98e5ab1aaaefb38621fd75c1856cfe93e6ffd124025cd0b139573f74f61"

      def install
        bin.install "coppeno"
      end
    end
  end

  test do
    system "#{bin}/coppeno --version"
  end
end
