# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Coppeno < Formula
  desc "coppeno"
  homepage "https://github.com/webcyou-org/coppeno"
  version "0.5.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/webcyou-org/coppeno/releases/download/v0.5.5/coppeno_darwin_arm64.tar.gz"
      sha256 "8afbb4f68c730b896ce277138fa37270ed894a54bd52092e2e13cfe2ae7d7111"

      def install
        bin.install "coppeno"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/webcyou-org/coppeno/releases/download/v0.5.5/coppeno_darwin_x86_64.tar.gz"
      sha256 "4fd117a74f71ed7ef178c476a4d0393ecd1833f23a5e17d1ecabaf0ba39db289"

      def install
        bin.install "coppeno"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/webcyou-org/coppeno/releases/download/v0.5.5/coppeno_linux_x86_64.tar.gz"
      sha256 "db979d923d80d57fb412aad57a9f90b8f51dc176d06a8d99bce26107b61c672d"

      def install
        bin.install "coppeno"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/webcyou-org/coppeno/releases/download/v0.5.5/coppeno_linux_arm64.tar.gz"
      sha256 "41ab41bf9a868d4437991eec94ed38bddfeefd2bed5728dfd3239584cdf1bbdc"

      def install
        bin.install "coppeno"
      end
    end
  end

  test do
    system "#{bin}/coppeno --version"
  end
end
